version: "3"
services:

  actinia:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ..:/src/actinia-parallel-plugin/.
      # - /home/.../grassdata/:/actinia_core/grassdb/
    ports:
      - "8088:8088"
    environment:
      - JOBTABLE_PW=actinia
    depends_on:
      - valkey
      - postgis
    cap_add:
      - SYS_PTRACE
    networks:
    -   actinia

  valkey:
    image: valkey/valkey:8.1-alpine
    volumes:
      - ./valkey_data:/data
    environment:
      - VALKEY_PASS_FILE=/data/config/.valkey
    command: [
      "sh", "-c",
      '
      docker-entrypoint.sh
      "/data/config/valkey.conf"
      --requirepass "$$(cat $$VALKEY_PASS_FILE)"
      '
    ]
    ports:
        - "6379:6379"
    networks:
    -   actinia

  postgis:
    image: postgis/postgis:14-3.2-alpine
    # network_mode: host
    environment:
      POSTGRES_USER: actinia
      POSTGRES_PASSWORD: actinia
    volumes:
      - ./postgresql_init_data:/docker-entrypoint-initdb.d
      - ./postgresql_data:/var/lib/postgresql/data:Z
    networks:
    -   actinia


networks:
  actinia:
    ipam:
      config:
        - subnet: 172.18.0.0/16
