version: "3"
services:

  actinia-test:
    build:
      context: ..
      dockerfile: docker/actinia-parallel-plugin-test/Dockerfile
    volumes:
      - ..:/src/actinia-parallel-plugin/.
    ports:
      - "8088:8088"
    environment:
      - JOBTABLE_PW=actinia
    depends_on:
      - redis-test
      - postgis-test
    cap_add:
      - SYS_PTRACE
    networks:
    -   actinia-test

  redis-test:
    image: redis:5.0.4-alpine
    volumes:
      - ./redis_data:/data
    environment:
      - REDIS_PASS_FILE=/data/config/.redis
    command: [
      "sh", "-c",
      '
      docker-entrypoint.sh
      "/data/config/redis.conf"
      --requirepass "$$(cat $$REDIS_PASS_FILE)"
      '
    ]
    ports:
        - "6379:6379"
    networks:
    -   actinia-test

  postgis-test:
    image: postgis/postgis:14-3.2-alpine
    # network_mode: host
    environment:
      POSTGRES_USER: actinia
      POSTGRES_PASSWORD: actinia
    volumes:
      - ./postgresql_init_data:/docker-entrypoint-initdb.d
      # - ./postgresql_data:/var/lib/postgresql/data:Z
    networks:
    -   actinia-test


networks:
  actinia-test:
    ipam:
      config:
        - subnet: 172.18.0.0/26
